# Example override for Linux
version: "3"
services:

  web:
    ports:
      - "8005:80"

  kibana:
    ports:
      - "5601:5601"

  phpmyadmin:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8040:80"

  php-debug:
    build:
      context: ./etc/php
      args:
        BASE_IMAGE: chialab/php-dev:7.2-fpm
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ${SHARED_DIR}
      - ./etc/php/settings.ini:/usr/local/etc/php/conf.d/z-settings.ini
      - ./etc/php/linux/settings.ini:/usr/local/etc/php/conf.d/zz-settings.ini
      - ./etc/php/linux/phpd:/usr/local/bin/phpd
    working_dir: ${WORKING_DIR}
    environment:
      COMPOSER_HOME: /var/www/var/composer
      PHP_IDE_CONFIG: serverName=${HOST}
