# Example override for Linux
version: "3"
services:

  web:
    ports:
      - "8005:80"
    networks:
      dockerdev-proxy:

  kibana:
    ports:
      - "5601:5601"
    networks:
      dockerdev-proxy:
      default:

  phpmyadmin:
    networks:
      dockerdev-proxy:
      default:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8040:80"

  php-debug:
    build:
      context: ./etc/php
      args:
        BASE_IMAGE: chialab/php-dev:7.2-fpm
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ${SHARED_DIR}
      - ./etc/php/settings.ini:/usr/local/etc/php/conf.d/z-settings.ini
      - ./etc/php/linux/settings.ini:/usr/local/etc/php/conf.d/zz-settings.ini
      - ./etc/php/linux/phpd:/usr/local/bin/phpd
      - ~/.composer:/composer
    working_dir: ${WORKING_DIR}
    environment:
      COMPOSER_HOME: /composer
      PHP_IDE_CONFIG: serverName=${HOST}

networks:
  dockerdev-proxy:
    external: true
