# Example override for Linux
version: "3"
services:
  web:
    networks:
      nginx-proxy:
    environment:
      LETSENCRYPT_HOST: ${HOST}
      HTTPS_METHOD: nohttp

  kibana:
    networks:
      nginx-proxy:
      default:
    environment:
      LETSENCRYPT_HOST: kibana.${HOST}
      HTTPS_METHOD: nohttp

  phpmyadmin:
    networks:
      nginx-proxy:
      default:
    environment:
      LETSENCRYPT_HOST: pma.${HOST}
      HTTPS_METHOD: nohttp

networks:
  nginx-proxy:
    external: true
