# Example override for Linux
version: "3"
services:
  web:
    networks:
      nginx-proxy:
    environment:
      LETSENCRYPT_HOST: ${HOST}
      HTTPS_METHOD: nohttp
    restart: always

  php:
    restart: always

  db:
    restart: always

  kibana:
    networks:
      nginx-proxy:
      default:
    environment:
      LETSENCRYPT_HOST: kibana.${HOST}
      HTTPS_METHOD: nohttp
    restart: always

  elasticsearch:
    restart: always

  phpmyadmin:
    networks:
      nginx-proxy:
      default:
    environment:
      LETSENCRYPT_HOST: pma.${HOST}
      HTTPS_METHOD: nohttp
    restart: always

networks:
  nginx-proxy:
    external: true
