# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Console\Command\:
        resource: '../src/Console/Command'
        tags: ['console.command']

    App\Indexer\IndexTweetSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: '@serializer.name_converter.camel_case_to_snake_case'
    Zend\Hydrator\ClassMethodsHydrator: ~
    Zend\Hydrator\HydratorInterface: '@Zend\Hydrator\ClassMethodsHydrator'

    Abraham\TwitterOAuth\TwitterOAuth:
        arguments:
            $consumerKey: '%twitter.consumer_key%'
            $consumerSecret : '%twitter.consumer_secret%'
            $oauthToken: '%twitter.oauth_token%'
            $oauthTokenSecret: '%twitter.oauth_token_secret%'

    Spatie\TwitterStreamingApi\UserStream:
        arguments:
            $accessToken: '%twitter.oauth_token%'
            $accessSecret: '%twitter.oauth_token_secret%'
            $consumerKey: '%twitter.consumer_key%'
            $consumerSecret: '%twitter.consumer_secret%'

    Spatie\TwitterStreamingApi\PublicStream:
        arguments:
            $accessToken: '%twitter.oauth_token%'
            $accessSecret: '%twitter.oauth_token_secret%'
            $consumerKey: '%twitter.consumer_key%'
            $consumerSecret: '%twitter.consumer_secret%'

    Elastica\Client:
        arguments:
            $config: '%elasticsearch.host%'
